apiVersion: v1
kind: Service
metadata:
  name: one-stop-service-ng
  namespace: one-stop-service-frontend
  labels:
    app: one-stop-service-ng
spec:
  selector:
    app: one-stop-service-ng
  ports:
    - name: web-http
      port: 80
      targetPort: 80
